### ISSUE TITLE
stocks.search_stock("bmw", limit=3) table = table_outer_div.find("table", {"class": "table"}) AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by DanielOberlechner** [Jhruzik/finanzen-fundamentals#13]
Hi I wanted to try your library but when I try the default commands this with bmw limit 3 I get this strange error.
Am I too dumb to use the library correct or has here something changed?

Kind regards,
Daniel Oberlechner

I was playing now a bit around, some functions work and others do not. Even those in the Readme most of them don't work. Is there something special to code, or should they just work out of the box?

**Comment by cierre** [comment]
Hi, 
I get the same, the funtion "stocks.get_estimates(stock=*)" works all other diidn't.
hopefully it will be fix, is a nice librery.

**Comment by Jhruzik** [comment]
Thanks for pointing that out! 

It seems that finanzen.net has changed the overall code of their site. Hence, the crawler can not find the necessary information. This is a problem not only for the search but for other functionality as well.

Since this library seems to be actively used, I'll start looking into it during the weekend and will hopefully be able to deliver a patch for that. I created a new branch for that bugfix under: https://github.com/Jhruzik/finanzen-fundamentals/tree/dev_bugfix

**Comment by Jhruzik** [comment]
I fixed the bug and the library should work again.

Please let me know if you encounter any further issues :)

Joshua
